config/routes.rb
Rails.application.routes.draw do

  resources :posts, only: [:index, :new, :create]

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  scope :publics, -> { where public:true }
  scope :privates, -> { where public:false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.publics.reverse
    @post = Post.new
    @tags = ['computer science', 'javascript', 'ruby on rails', 'bootstrap', 'photoshop', 'photography', 'usability', 'great products']
  end

  # GET /posts/1
  # GET /posts/1.json
  # def show
  # end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  # def edit
  # end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_path, notice: 'Thank you for your message.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  # def update
  #   respond_to do |format|
  #     if @post.update(post_params)
  #       format.html { redirect_to @post, notice: 'Post was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @post }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @post.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /posts/1
  # DELETE /posts/1.json
  # def destroy
  #   @post.destroy
  #   respond_to do |format|
  #     format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:message, :name, :email, :public)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Antti Suniala', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><a href="http://www.github.com/Sunave"><i class="fa fa-github"></i></a></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Antti Suniala" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Anttisuniala" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <div class="container">
      <main role="main">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </main>
    </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: { class:"form-horizontal"} do |f| %>
  <fieldset>
    <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
          <% @post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <legend>Leave a message</legend>
    <%= f.check_box :public, { checked: true } %> Add to shoutbox (otherwise it's private)<br>

    <div class="input-group input-group-lg">
      <%= f.text_area :message, class:"form-control", placeholder: "Your message" %>
      <span class="input-group-sm">
        <%= f.text_field :name, class:"form-control", placeholder: "Name" %>
        <%= f.text_field :email, class:"form-control", placeholder: "Email (not shown to anyone but me)" %>
      </span>
    </div>
    <%= f.submit "Send", class: "btn btn-success btn-lg" %>
  </fieldset>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="jumbotron text-center">

  <h1>Hello world</h1>
  <p class="lead">I am Antti.</p>
  <h1>
    <a href="http://github.com/Sunave" target="_blank"><i class="fa fa-github"></i></a>
  </h1>
  <img src="<%= asset_path('antti.jpg') %>" class="img-circle img-responsive">
</div>


<div class="panel panel-default">
  <div class="panel-heading">
    <h2 class="panel-title">Keywords and info</h2>
  </div>
  <div class="panel-body">
    <p>I'm a computer science and usability enthusiast. My interests include</p>
    <h4>
      <% @tags.each do |tag| %>
        <span class="label label-default label"><i class="fa fa-slack"></i> <%= tag %></span>
      <% end %>
    </h4>

    <p>I live in Helsinki, Finland, where I'm studying Computer Science at University of Helsinki.</p>

    <h3>Contact:</h3>
    <div class="list-group-item"><i class="fa fa-github fa-lg fa-fw"></i> Check my Github projects at <strong><a href="http://github.com/Sunave" target="_blank">github.com/Sunave</a></strong></div>
    <div class="list-group-item"><i class="fa fa-envelope fa-lg fa-fw"></i> Contact by email <strong>my first name</strong> @ <strong>anttisuniala.fi</strong></div>
    <div class="list-group-item"><i class="fa fa-comments fa-lg fa-fw"></i> In IRC you can reach me via nick <strong>sunave</strong> at <strong>IRCnet</strong></div>
    <div class="list-group-item"><i class="fa fa-comment fa-lg fa-fw"></i> Or leave a comment below!</div>

  </div>
</div>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Posts by others</h3>
  </div>
  <div class="panel-body">
    <div class="list-group">
      <% @posts.each do |post| %>
        <h4 class="list-group-item-heading"><%= post.name %>:</h4>
        <div class="list-group-item"><%= post.message %></div>
      <% end %>
    </div>

    <%= render 'form' %>
  </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @post.message %>
</p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @post.email %>
</p>

<p>
  <strong>Public:</strong>
  <%= @post.public %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>